### ISSUE TITLE
clean_snapshots: ValueError: invalid literal for int() with base 10: '4.4.0'

### ISSUE THREAD

**Issue by GerardGarcia** [fearedbliss/bliss-zfs-scripts#1]
I'm getting the following error with the call: /usr/local/sbin/clean_snapshots -f -p <pool> -t zfs. It happens when it needs to remove snapshots, otherwise it does not show any error.

Traceback (most recent call last):
  File "/usr/local/sbin/clean_snapshots", line 619, in <module>
    cleaner.start()
  File "/usr/local/sbin/clean_snapshots", line 62, in start
    self.fs_manager.check_snapshots()
  File "/usr/local/sbin/clean_snapshots", line 365, in check_snapshots
    self.slicer(snap)
  File "/usr/local/sbin/clean_snapshots", line 466, in slicer
    super().slicer(a_snap, date_split)
  File "/usr/local/sbin/clean_snapshots", line 427, in slicer
    year = int(date_split[0])
ValueError: invalid literal for int() with base 10: '4.4.0'

I'm using Python 3.4.3 in Gentoo linux.

**Comment by fearedbliss** [comment]
You are missing the pool parameter in the command since you are passing -p but no pool name.

From the usage output of the program:

clean_snapshots -f -p <pool> -t zfs

closing.

**Comment by fearedbliss** [comment]
Aarg... Github filtered out my symbols..

clean_snapshots -f -p [pool] -t zfs

**Comment by GerardGarcia** [comment]
I'm passing the pool name but github filtered the symbol too..

**Comment by fearedbliss** [comment]
Ah ok! How are your snapshots named? They need to be in a specific format.
Example:

tank/gentoo/root@2016-02-19-1300-01-HOURLY

"Date must be in YYYY-mm-dd-MMSS format!

**Comment by GerardGarcia** [comment]
Right, solved! I had one snapshot without the correct date format. 

Thanks

**Comment by fearedbliss** [comment]
Nice :). Glad everything is good. Closing.
