### ISSUE TITLE
unable to install kernel

### ISSUE THREAD

**Issue by ip75** [fearedbliss/bliss-zfs-scripts#3]
https://wiki.gentoo.org/wiki/User:Fearedbliss/Installing_Gentoo_Linux_On_ZFS  is not work

![Screenshot_3](https://user-images.githubusercontent.com/3886308/66731054-edc52400-ee5d-11e9-93fc-20e6ad7d57c8.png)

**Comment by fearedbliss** [comment]
Hey @ip75,

As stated in the guide, it is no longer being maintained. I've also retired from Gentoo Development last year and have switched over to FreeBSD for my server. FreeBSD 13 now has OpenZFS which means Linux and FreeBSD have the same exact binaries, we just don't have to worry about the Linux Kernel's GPLv2 conflict with OpenZFS's CDDL, which yields greater system stability and integration.

Take care,

Jonathan
